import mongoose from 'mongoose';

const GameCatalogSchema = new mongoose.Schema({
  // ── Inventori Riil Google Drive ──
  name: {
    type: String,
    required: true,
    index: true,
  },
  folderId: {
    type: String,
    required: true,
    unique: true, // 1 folder game = 1 entry, tidak boleh duplikat
  },
  ownerEmail: {
    type: String,
    required: true,
    index: true,
  },
  fileCount: {
    type: Number,
    default: 0,
  },
  totalSize: {
    type: Number, // bytes murni dari scanning Google Drive
    default: 0,
  },
  sendCount: {
    type: Number, // counter pengiriman
    default: 0,
  },
  lastSyncedAt: {
    type: Date,
    default: null,
  },

  // ── Aset & Metadata Resmi Steam / SteamDB ──
  steamAppId: {
    type: String,
    default: null,
    index: true,
  },
  cleanTitle: {
    type: String,
    default: null,
  },
  coverImageUrl: {
    type: String, // library_600x900.jpg dari CDN Steam
    default: null,
  },
  headerBannerUrl: {
    type: String, // header.jpg dari CDN Steam
    default: null,
  },
  screenshots: {
    type: [String],
    default: [],
  },
  genres: {
    type: [String],
    default: [],
  },
  tags: {
    type: [String],
    default: [],
  },
  shortDescription: {
    type: String,
    default: '',
  },
  releaseYear: {
    type: String,
    default: '',
  },
  developer: {
    type: String,
    default: '',
  },
  specs: {
    minimum: {
      os: { type: String, default: '' },
      cpu: { type: String, default: '' },
      ram: { type: String, default: '' },
      gpu: { type: String, default: '' },
      storage: { type: String, default: '' },
      directx: { type: String, default: '' },
    },
    recommended: {
      os: { type: String, default: '' },
      cpu: { type: String, default: '' },
      ram: { type: String, default: '' },
      gpu: { type: String, default: '' },
      storage: { type: String, default: '' },
      directx: { type: String, default: '' },
    },
  },

  // ── Storefront & Status ──
  packageType: {
    type: String,
    default: 'PRE-INSTALLED',
  },
  fileVersion: {
    type: String,
    default: '',
  },
  shopeeUrl: {
    type: String,
    default: '',
  },
  isPublished: {
    type: Boolean,
    default: true,
  },
  firestoreSyncedAt: {
    type: Date,
    default: null,
  },

  // ── Pipeline Status ──
  pipelineStatus: {
    type: String,
    enum: [
      'none',          // belum ada proses
      'downloading',   // sedang didownload
      'downloaded',    // selesai download, belum di-prep
      'extracted',     // sudah diekstrak / folder game siap
      'uploading',     // sedang diupload ke GDrive
      'on_drive',      // sudah ada di GDrive
      'listing_ready', // slide Shopee sudah digenerate, belum di-listing
      'listed'         // sudah live di Shopee
    ],
    default: 'none',
    index: true
  },

  // ── Shopee Listing ──
  shopeeListed: {
    type: Boolean,
    default: false,
    index: true
  },
  shopeeListedAt: {
    type: Date,
    default: null
  },
  // NOTE: shopeeUrl field already exists — keep it, ensure it's filled on mark-listed

  // ── Listing Assets (generated by Scout/Listing Studio) ──
  listingAssets: {
    seoTitle: { type: String, default: '' },
    description: { type: String, default: '' },
    slidesFolderPath: { type: String, default: '' }, // absolute local path to generated slides folder
    generatedAt: { type: Date, default: null }
  },

  // ── Upload Tracking ──
  lastUploadedAt: { type: Date, default: null },
  uploadMode: {
    type: String,
    enum: ['new', 'update', ''],
    default: ''
  },
  driveWorkspaceEmail: { type: String, default: '' }, // which GDrive account was used
}, { timestamps: true });

// Full-text search index untuk pencarian game
GameCatalogSchema.index({ name: 'text', cleanTitle: 'text' });

export default mongoose.models.GameCatalog || mongoose.model('GameCatalog', GameCatalogSchema);
